---
- name: Setup Wazuh
  hosts: wazuh_dashboard_server
  become: true
  gather_facts: true
  vars:
    instances: # A certificate will be generated for every node using the name as CN
      node1:
        name: "{{ indexer_node_name }}" # Must be equal to indexer_node_name
        ip: "{{ indexer_network_host }}"
        role: "indexer"
    indexer_cluster_nodes:
      - "{{ indexer_network_host }}"
  tasks:
    - name: See group_names
      debug:
        var: group_names

    - name: Generate certificates
      include_role:
        name: wazuh/wazuh-indexer
      # become: no
      vars:
        perform_installation: false

      tags:
        - generate-certs

    - name: Install Wazuh Server
      block:
        # Runs in port 9200
        - name: Install Indexer # systemctl status wazuh-indexer
          include_role:
            name: wazuh/wazuh-indexer
          tags:
            - wazuh_indexer_server
          when: "'wazuh_indexer_server' in group_names"

        - name: Install Dashboard # systemctl status wazuh-dashboard
          include_role:
            name: wazuh/wazuh-dashboard
          tags:
            - wazuh_dashboard_server
          when: "'wazuh_dashboard_server' in group_names"
          vars:
            ansible_shell_allow_world_readable_temp: true

    # Runs in port 1514
    - name: Setup Wazuh Manager
      block:
        - name: Install Wazuh Manager # systemctl status wazuh-manager
          include_role:
            name: wazuh/ansible-wazuh-manager
          # tags:
          #   - wazuh_manager_server
          # when: "'wazuh_manager_server' in group_names"

        # Sudo filebeat test output
        - name: Install Wazuh Manager # systemctl status filebeat
          include_role:
            name: wazuh/ansible-filebeat-oss
      tags: wazuh-manager
      vars:
        # indicates the host group of the Wazuh indexer cluster
        filebeat_output_indexer_hosts:
          - "{{ indexer_network_host }}"
        filebeat_node_name: "{{ indexer_node_name }}"
        wazuh_manager_labels:
          enable: true
          list:
            - key: Env
              value: Production
        # wazuh_manager_indexer:
        #   enabled: "yes"
        #   hosts: "{{ indexer_network_host }}"
